"""Compatibility shim for algorithm constants module path."""

from models.config.algorithm import (
    ALPHA,
    BETA,
    INTERACTION_SENSITIVITY_BASELINE,
    INTERACTION_SENSITIVITY_DEMO_STRONG,
    INTERACTION_SENSITIVITY_MODES,
    INTERACTION_WEIGHTS,
    PROFILE_WEIGHTS,
)

__all__ = [
    "ALPHA",
    "BETA",
    "INTERACTION_WEIGHTS",
    "INTERACTION_SENSITIVITY_BASELINE",
    "INTERACTION_SENSITIVITY_DEMO_STRONG",
    "INTERACTION_SENSITIVITY_MODES",
    "PROFILE_WEIGHTS",
]
