[pytest]
filterwarnings =
    ignore::DeprecationWarning:httpx.*:
    ignore::DeprecationWarning:starlette.*:
    ignore::UserWarning:umap.*:
    ignore::DeprecationWarning:asyncio.*:
    ignore::DeprecationWarning:fastapi.*:
