"""Regression tests for the UMAP projection pipeline.

Snapshot ground truth: tests/fixtures/umap_regression_snapshot.npy
Generated by: python tests/fixtures/generate_snapshot.py
umap-learn version pinned: 0.5.11

To regenerate after a umap-learn upgrade:
    cd backend && python tests/fixtures/generate_snapshot.py
This is expected after version upgrades — not a bug.
"""

import os
import numpy as np
import pytest

SNAPSHOT_PATH = os.path.join(
    os.path.dirname(__file__), "..", "fixtures", "umap_regression_snapshot.npy"
)
N = 20
SEED = 0


def _build_fixed_distance_matrix() -> np.ndarray:
    rng = np.random.default_rng(SEED)
    raw = rng.random((N, N))
    sym = (raw + raw.T) / 2
    np.fill_diagonal(sym, 0.0)
    return sym.clip(0.0, 1.0)


def test_snapshot_valid():
    """Committed snapshot is finite, correct shape, no NaN."""
    snapshot = np.load(SNAPSHOT_PATH)
    assert snapshot.shape == (N, 2), f"Unexpected shape: {snapshot.shape}"
    assert snapshot.dtype in (np.float32, np.float64)
    assert not np.any(np.isnan(snapshot)), "Snapshot contains NaN"
    assert not np.any(np.isinf(snapshot)), "Snapshot contains Inf"


def test_umap_regression():
    """project() on the fixed distance matrix matches the committed snapshot."""
    from services.map.projector import project

    dist = _build_fixed_distance_matrix()
    coords = project(dist)
    snapshot = np.load(SNAPSHOT_PATH)

    assert coords.shape == snapshot.shape, (
        f"Shape mismatch: {coords.shape} vs {snapshot.shape}"
    )
    np.testing.assert_allclose(
        coords, snapshot, atol=1e-4,
        err_msg="UMAP output diverged from snapshot — regenerate if umap-learn was upgraded",
    )


def test_full_pipeline_regression():
    """build_combined_distance() + project() produces correct shape with zero diagonal."""
    from services.map.distance import build_combined_distance
    from services.map.projector import project
    from services.map.contracts import PipelineInput
    from models.user import UserProfile  # noqa: F811

    n = 10
    profiles = [
        UserProfile(id=str(i), nickname=f"u{i}", interests=["coding"])
        for i in range(n)
    ]

    pipeline_input = PipelineInput(profiles=profiles, interactions=[])
    dist = build_combined_distance(pipeline_input)
    assert dist.shape == (n, n)
    assert np.all(np.diag(dist) == 0.0), "Diagonal of distance matrix must be zero"

    coords = project(dist)
    assert coords.shape == (n, 2)
    assert not np.any(np.isnan(coords))
